# Generated by Django 5.2.4 on 2025-08-06 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='Post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
            preserve_default=False,
        ),
    ]
