# Generated by Django 5.2.4 on 2025-08-06 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_comments_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='approach',
            new_name='approved',
        ),
    ]
